name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      6.6.0
          host:         mac
          target:       desktop
          dir:          ${{ runner.temp }}
          setup-python: false
          cache:        true
      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest -C Debug --output-on-failure
